version: '3.8'

services:
  app:
    build: .
    container_name: stange_castle_app
    restart: unless-stopped
    volumes:
      # MAPEAMENTO DE VOLUMES: Impede que os seus dados sejam apagados se o Docker reiniciar
      - ./StangeTreasure_Drive:/app/StangeTreasure_Drive
      - ./ListaNegra.txt:/app/ListaNegra.txt
      - ./UsuariosCadastrados.txt:/app/UsuariosCadastrados.txt
      - ./WikiContent.html:/app/WikiContent.html
      - ./appsettings.json:/app/appsettings.json
    networks:
      - homelab_net

  nginx:
    image: nginx:latest
    container_name: stange_castle_nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - homelab_net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: stange_castle_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token 350f14a0-545f-453b-b122-8f1a97fc32c5
    networks:
      - homelab_net

networks:
  homelab_net:
    driver: bridge