version: '3.8'

services:
  app:
    build: .
    container_name: stange_castle_app
    restart: unless-stopped
    ports:
      - "4233:4233"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./StangeTreasure_Drive:/app/StangeTreasure_Drive
      - ./ListaNegra.txt:/app/ListaNegra.txt
      - ./UsuariosCadastrados.txt:/app/UsuariosCadastrados.txt
      - ./WikiContent.html:/app/WikiContent.html
      - ./.backlog.txt:/app/.backlog.txt
      - ./appsettings.json:/app/appsettings.json
    networks:
      - homelab_net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: stange_castle_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiZTFiYzI3NDY0OGRiOTEzZDk1MjIzOWQ0NTcyYjYwNjMiLCJ0IjoiMzUwZjE0YTAtNTQ1Zi00NTNiLWIxMjItOGYxYTk3ZmMzMmM1IiwicyI6Ik5tVTBObUZqT0dZdE56azNPQzAwWkRsakxUa3lZVFl0TlRnek16a3pNRGt3TlRVNSJ9
    networks:
      - homelab_net

networks:
  homelab_net:
    driver: bridge
  