server {
    listen 80;
    server_name stangecastle.com.br;

    location / {
        proxy_pass http://app:4233;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection keep-alive;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Permite upload de ficheiros grandes (Ex: 500MB) para o seu Drive
        client_max_body_size 500M; 
    }
}